# Generated by Django 5.1.7 on 2026-04-19 09:34

import django.db.models.deletion
import groomer_jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0006_merge_20260418_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingServiceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kondisi_bulu', models.TextField()),
                ('kondisi_kulit', models.TextField()),
                ('kondisi_telinga', models.TextField()),
                ('kondisi_kuku', models.TextField()),
                ('perilaku_hewan', models.TextField()),
                ('catatan_tambahan', models.TextField(blank=True, null=True)),
                ('foto_bukti_layanan', models.ImageField(upload_to='grooming_service_forms/', validators=[groomer_jobs.models.validate_image_file])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grooming_service_form', to='booking.bookingitem')),
            ],
            options={
                'db_table': 'grooming_service_forms',
            },
        ),
    ]
