# Generated by Django 5.2 on 2026-04-15 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jenis', models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=10)),
                ('ras', models.CharField(max_length=100)),
                ('umur', models.IntegerField(help_text='Umur dalam bulan')),
                ('berat', models.FloatField(help_text='Berat dalam kg')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('owner', 'name'), name='unique_active_pet_per_user')],
            },
        ),
    ]
