# Generated by Django 5.2 on 2026-04-08 13:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_deleted_at_pet_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('owner', 'name'), name='unique_active_pet_per_user'),
        ),
    ]
