# Generated by Django 5.2 on 2026-04-15 03:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('animal_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], max_length=10)),
                ('package_type', models.CharField(choices=[('grooming', 'Grooming'), ('additional', 'Additional')], default='grooming', max_length=10)),
                ('description', models.TextField()),
                ('duration_min', models.IntegerField(choices=[(30, '30 menit'), (60, '60 menit'), (90, '90 menit'), (120, '120 menit')])),
                ('is_all_size', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'packages',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'animal_type'), name='unique_active_package_name_per_animal')],
            },
        ),
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2, null=True)),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='packages.package')),
            ],
            options={
                'db_table': 'package_prices',
                'unique_together': {('package', 'size')},
            },
        ),
    ]
