# Generated by Django 5.2.11 on 2026-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='recommendation_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
