# Generated by Django 5.2.12 on 2026-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
