# Generated by Django 4.2.28 on 2026-03-06 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageprice',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
