# Generated by Django 4.2.28 on 2026-03-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_packageprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_all_size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('grooming', 'Grooming'), ('additional', 'Additional')], default='grooming', max_length=10),
        ),
    ]
