# Generated by Django 4.2.28 on 2026-03-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_is_all_size_package_package_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'animal_type'), name='unique_active_package_name_per_animal'),
        ),
    ]
