# Generated by Django 5.2.7 on 2026-02-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('groomer', 'Groomer'), ('manager', 'Manager'), ('superadmin', 'Superadmin')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Groomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('home', 'Home'), ('clinic', 'Clinic')], max_length=10)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'groomer'}, on_delete=django.db.models.deletion.CASCADE, related_name='groomer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
