# Generated by Django 5.2.11 on 2026-02-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE TYPE role_enum AS ENUM ('customer', 'staff', 'groomer', 'manager');",
            reverse_sql="DROP TYPE role_enum;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE users ALTER COLUMN role TYPE role_enum USING role::role_enum;",
            reverse_sql="ALTER TABLE users ALTER COLUMN role TYPE varchar(20);"
        ),
        migrations.RunSQL(
            sql="CREATE TYPE service_type_enum AS ENUM ('home', 'clinic');",
            reverse_sql="DROP TYPE service_type_enum;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE accounts_groomer ALTER COLUMN service_type TYPE service_type_enum USING service_type::service_type_enum;",
            reverse_sql="ALTER TABLE accounts_groomer ALTER COLUMN service_type TYPE varchar(10);"
        ),
    ]
