# Generated by Django 4.2.28 on 2026-04-19 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_groomer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
