# Generated by Django 5.1.1 on 2026-04-06 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_groomer_deleted_at_groomer_is_deleted'),
        ('packages', '0005_package_unique_active_package_name_per_animal'),
        ('pet', '0002_pet_deleted_at_pet_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('clinic', 'Clinic'), ('home', 'Home')], max_length=10)),
                ('tanggal', models.DateField()),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('total_durasi', models.PositiveIntegerField(help_text='Total durasi dalam menit')),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('on_the_way', 'On the way'), ('arrived', 'Arrived'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=10)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='accounts.groomer')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-tanggal', '-waktu_mulai', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga_paket', models.DecimalField(decimal_places=2, max_digits=12)),
                ('durasi_paket', models.PositiveIntegerField(help_text='Durasi paket dalam menit')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.booking')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='packages.package')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='pet.pet')),
            ],
            options={
                'db_table': 'booking_items',
            },
        ),
        migrations.CreateModel(
            name='BookingItemAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('durasi', models.PositiveIntegerField(help_text='Durasi additional dalam menit')),
                ('additional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_item_additionals', to='packages.package')),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='booking.bookingitem')),
            ],
            options={
                'db_table': 'booking_item_additionals',
            },
        ),
    ]
