# Generated by Django 5.1.7 on 2026-05-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '000X_bookingreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingreview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
