# Generated by Django 5.2 on 2026-04-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='grooming_notes',
            field=models.TextField(blank=True, help_text='Catatan hasil grooming yang diisi oleh groomer setelah layanan selesai', null=True),
        ),
    ]
