# Generated by Django 4.2.28 on 2026-04-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
