# Generated by Django 6.0.2 on 2026-05-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_alter_bookingreview_id'),
    ]

    operations = [
    ]
