# Generated by Django 5.1.1 on 2026-04-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='original_tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_waktu_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='original_waktu_selesai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('on_the_way', 'On the way'), ('arrived', 'Arrived'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
