# Generated by Django 5.1.1 on 2026-04-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_original_tanggal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('service_started', 'Service started'), ('service_completed', 'Service completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
