# Generated by Django 4.2.28 on 2026-04-17 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_status'),
        ('booking', '0005_alter_booking_status'),
    ]

    operations = [
    ]
