# Generated by Django 4.2.28 on 2026-04-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_merge_20260418_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='package_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bookingitemadditional',
            name='additional_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
