# Generated by Django 5.2 on 2026-02-28 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_pet_owner_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
