# Generated by Django 4.2.28 on 2026-04-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
